package uk.cyruscastle.www.ui.theme

import androidx.compose.material3.TextFieldDefaults
import androidx.compose.runtime.Composable

@Composable
fun WindowTextFieldColor() = TextFieldDefaults.colors().copy(
    focusedTextColor = ColorPalette.STROKE,
    unfocusedTextColor = ColorPalette.STROKE,
//    disabledTextColor = this.disabledTextColor,
//    errorTextColor = this.errorTextColor,
    focusedContainerColor = ColorPalette.BG,
    unfocusedContainerColor = ColorPalette.BG,
    disabledContainerColor = ColorPalette.BG,
//    errorContainerColor = this.errorContainerColor,
//    cursorColor = this.cursorColor,
//    errorCursorColor = this.errorCursorColor,
//    textSelectionColors = this.textSelectionColors,
//    focusedIndicatorColor = this.focusedIndicatorColor,
//    unfocusedIndicatorColor = this.unfocusedIndicatorColor,
//    disabledIndicatorColor = this.disabledIndicatorColor,
//    errorIndicatorColor = this.errorIndicatorColor,
//    focusedLeadingIconColor = this.focusedLeadingIconColor,
//    unfocusedLeadingIconColor = this.unfocusedLeadingIconColor,
//    disabledLeadingIconColor = this.disabledLeadingIconColor,
//    errorLeadingIconColor = this.errorLeadingIconColor,
//    focusedTrailingIconColor = this.focusedTrailingIconColor,
//    unfocusedTrailingIconColor = this.unfocusedTrailingIconColor,
//    disabledTrailingIconColor = this.disabledTrailingIconColor,
//    errorTrailingIconColor = this.errorTrailingIconColor,
//    focusedLabelColor = this.focusedLabelColor,
//    unfocusedLabelColor = this.unfocusedLabelColor,
//    disabledLabelColor = this.disabledLabelColor,
//    errorLabelColor = this.errorLabelColor,
//    focusedPlaceholderColor = this.focusedPlaceholderColor,
//    unfocusedPlaceholderColor = this.unfocusedPlaceholderColor,
//    disabledPlaceholderColor = this.disabledPlaceholderColor,
//    errorPlaceholderColor = this.errorPlaceholderColor,
//    focusedSupportingTextColor = this.focusedSupportingTextColor,
//    unfocusedSupportingTextColor = this.unfocusedSupportingTextColor,
//    disabledSupportingTextColor = this.disabledSupportingTextColor,
//    errorSupportingTextColor = this.errorSupportingTextColor,
//    focusedPrefixColor = this.focusedPrefixColor,
//    unfocusedPrefixColor = this.unfocusedPrefixColor,
//    disabledPrefixColor = this.disabledPrefixColor,
//    errorPrefixColor = this.errorPrefixColor,
//    focusedSuffixColor = this.focusedSuffixColor,
//    unfocusedSuffixColor = this.unfocusedSuffixColor,
//    disabledSuffixColor = this.disabledSuffixColor,
//    errorSuffixColor = this.errorSuffixColor
)